// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _EVORESISTANCE_RCPPR6_PRE_HPP_
#define _EVORESISTANCE_RCPPR6_PRE_HPP_

#include <RcppCommon.h>


namespace EvoResistance {
namespace RcppR6 {
template <typename T> class RcppR6;
}
}



namespace Rcpp {
template <typename T> SEXP wrap(const EvoResistance::RcppR6::RcppR6<T>&);
namespace traits {
template <typename T> class Exporter<EvoResistance::RcppR6::RcppR6<T> >;
}

template <> SEXP wrap(const parameters&);
template <> parameters as(SEXP);
template <> SEXP wrap(const trajectory&);
template <> trajectory as(SEXP);
template <> SEXP wrap(const fixation_probability&);
template <> fixation_probability as(SEXP);
}

#endif
