// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/EvoResistanceNHEJ.h"
#include <Rcpp.h>

using namespace Rcpp;

// p_mu
double p_mu(parameters& P, trajectory& T, fixation_probability& F);
RcppExport SEXP EvoResistanceNHEJ_p_mu(SEXP PSEXP, SEXP TSEXP, SEXP FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< parameters& >::type P(PSEXP);
    Rcpp::traits::input_parameter< trajectory& >::type T(TSEXP);
    Rcpp::traits::input_parameter< fixation_probability& >::type F(FSEXP);
    rcpp_result_gen = Rcpp::wrap(p_mu(P, T, F));
    return rcpp_result_gen;
END_RCPP
}
// p_delta
double p_delta(parameters& P, trajectory& T, fixation_probability& F);
RcppExport SEXP EvoResistanceNHEJ_p_delta(SEXP PSEXP, SEXP TSEXP, SEXP FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< parameters& >::type P(PSEXP);
    Rcpp::traits::input_parameter< trajectory& >::type T(TSEXP);
    Rcpp::traits::input_parameter< fixation_probability& >::type F(FSEXP);
    rcpp_result_gen = Rcpp::wrap(p_delta(P, T, F));
    return rcpp_result_gen;
END_RCPP
}
// p_sgv
double p_sgv(parameters& P, fixation_probability& F);
RcppExport SEXP EvoResistanceNHEJ_p_sgv(SEXP PSEXP, SEXP FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< parameters& >::type P(PSEXP);
    Rcpp::traits::input_parameter< fixation_probability& >::type F(FSEXP);
    rcpp_result_gen = Rcpp::wrap(p_sgv(P, F));
    return rcpp_result_gen;
END_RCPP
}
// parameters__ctor
parameters parameters__ctor(double x0, double c, double delta, double mu, double sdo, double sdr, double sro, double sdd, double srr, double Ne, double N, double sigma);
RcppExport SEXP EvoResistanceNHEJ_parameters__ctor(SEXP x0SEXP, SEXP cSEXP, SEXP deltaSEXP, SEXP muSEXP, SEXP sdoSEXP, SEXP sdrSEXP, SEXP sroSEXP, SEXP sddSEXP, SEXP srrSEXP, SEXP NeSEXP, SEXP NSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sdo(sdoSEXP);
    Rcpp::traits::input_parameter< double >::type sdr(sdrSEXP);
    Rcpp::traits::input_parameter< double >::type sro(sroSEXP);
    Rcpp::traits::input_parameter< double >::type sdd(sddSEXP);
    Rcpp::traits::input_parameter< double >::type srr(srrSEXP);
    Rcpp::traits::input_parameter< double >::type Ne(NeSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__ctor(x0, c, delta, mu, sdo, sdr, sro, sdd, srr, Ne, N, sigma));
    return rcpp_result_gen;
END_RCPP
}
// parameters__x0__get
double parameters__x0__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__x0__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__x0__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__x0__set
void parameters__x0__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__x0__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__x0__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__c__get
double parameters__c__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__c__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__c__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__c__set
void parameters__c__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__c__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__c__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__delta__get
double parameters__delta__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__delta__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__delta__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__delta__set
void parameters__delta__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__delta__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__delta__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__mu__get
double parameters__mu__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__mu__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__mu__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__mu__set
void parameters__mu__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__mu__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__mu__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__sdo__get
double parameters__sdo__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__sdo__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__sdo__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__sdo__set
void parameters__sdo__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__sdo__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__sdo__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__sdr__get
double parameters__sdr__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__sdr__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__sdr__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__sdr__set
void parameters__sdr__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__sdr__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__sdr__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__sro__get
double parameters__sro__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__sro__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__sro__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__sro__set
void parameters__sro__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__sro__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__sro__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__sdd__get
double parameters__sdd__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__sdd__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__sdd__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__sdd__set
void parameters__sdd__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__sdd__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__sdd__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__srr__get
double parameters__srr__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__srr__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__srr__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__srr__set
void parameters__srr__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__srr__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__srr__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__Ne__get
double parameters__Ne__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__Ne__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__Ne__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__Ne__set
void parameters__Ne__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__Ne__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__Ne__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__N__get
double parameters__N__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__N__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__N__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__N__set
void parameters__N__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__N__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__N__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// parameters__sigma__get
double parameters__sigma__get(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_);
RcppExport SEXP EvoResistanceNHEJ_parameters__sigma__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(parameters__sigma__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// parameters__sigma__set
void parameters__sigma__set(EvoResistanceNHEJ::RcppR6::RcppR6<parameters> obj_, double value);
RcppExport SEXP EvoResistanceNHEJ_parameters__sigma__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<parameters> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    parameters__sigma__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// trajectory__ctor
trajectory trajectory__ctor(parameters& P);
RcppExport SEXP EvoResistanceNHEJ_trajectory__ctor(SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< parameters& >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(trajectory__ctor(P));
    return rcpp_result_gen;
END_RCPP
}
// trajectory__x
double trajectory__x(EvoResistanceNHEJ::RcppR6::RcppR6<trajectory> obj_, int t);
RcppExport SEXP EvoResistanceNHEJ_trajectory__x(SEXP obj_SEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<trajectory> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(trajectory__x(obj_, t));
    return rcpp_result_gen;
END_RCPP
}
// trajectory__t_fix__get
int trajectory__t_fix__get(EvoResistanceNHEJ::RcppR6::RcppR6<trajectory> obj_);
RcppExport SEXP EvoResistanceNHEJ_trajectory__t_fix__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<trajectory> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(trajectory__t_fix__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// trajectory__t_fix__set
void trajectory__t_fix__set(EvoResistanceNHEJ::RcppR6::RcppR6<trajectory> obj_, int value);
RcppExport SEXP EvoResistanceNHEJ_trajectory__t_fix__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<trajectory> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    trajectory__t_fix__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// fixation_probability__ctor
fixation_probability fixation_probability__ctor(parameters& P, trajectory& T);
RcppExport SEXP EvoResistanceNHEJ_fixation_probability__ctor(SEXP PSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< parameters& >::type P(PSEXP);
    Rcpp::traits::input_parameter< trajectory& >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(fixation_probability__ctor(P, T));
    return rcpp_result_gen;
END_RCPP
}
// fixation_probability__pi
double fixation_probability__pi(EvoResistanceNHEJ::RcppR6::RcppR6<fixation_probability> obj_, int t);
RcppExport SEXP EvoResistanceNHEJ_fixation_probability__pi(SEXP obj_SEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< EvoResistanceNHEJ::RcppR6::RcppR6<fixation_probability> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(fixation_probability__pi(obj_, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"EvoResistanceNHEJ_p_mu", (DL_FUNC) &EvoResistanceNHEJ_p_mu, 3},
    {"EvoResistanceNHEJ_p_delta", (DL_FUNC) &EvoResistanceNHEJ_p_delta, 3},
    {"EvoResistanceNHEJ_p_sgv", (DL_FUNC) &EvoResistanceNHEJ_p_sgv, 2},
    {"EvoResistanceNHEJ_parameters__ctor", (DL_FUNC) &EvoResistanceNHEJ_parameters__ctor, 12},
    {"EvoResistanceNHEJ_parameters__x0__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__x0__get, 1},
    {"EvoResistanceNHEJ_parameters__x0__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__x0__set, 2},
    {"EvoResistanceNHEJ_parameters__c__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__c__get, 1},
    {"EvoResistanceNHEJ_parameters__c__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__c__set, 2},
    {"EvoResistanceNHEJ_parameters__delta__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__delta__get, 1},
    {"EvoResistanceNHEJ_parameters__delta__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__delta__set, 2},
    {"EvoResistanceNHEJ_parameters__mu__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__mu__get, 1},
    {"EvoResistanceNHEJ_parameters__mu__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__mu__set, 2},
    {"EvoResistanceNHEJ_parameters__sdo__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__sdo__get, 1},
    {"EvoResistanceNHEJ_parameters__sdo__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__sdo__set, 2},
    {"EvoResistanceNHEJ_parameters__sdr__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__sdr__get, 1},
    {"EvoResistanceNHEJ_parameters__sdr__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__sdr__set, 2},
    {"EvoResistanceNHEJ_parameters__sro__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__sro__get, 1},
    {"EvoResistanceNHEJ_parameters__sro__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__sro__set, 2},
    {"EvoResistanceNHEJ_parameters__sdd__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__sdd__get, 1},
    {"EvoResistanceNHEJ_parameters__sdd__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__sdd__set, 2},
    {"EvoResistanceNHEJ_parameters__srr__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__srr__get, 1},
    {"EvoResistanceNHEJ_parameters__srr__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__srr__set, 2},
    {"EvoResistanceNHEJ_parameters__Ne__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__Ne__get, 1},
    {"EvoResistanceNHEJ_parameters__Ne__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__Ne__set, 2},
    {"EvoResistanceNHEJ_parameters__N__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__N__get, 1},
    {"EvoResistanceNHEJ_parameters__N__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__N__set, 2},
    {"EvoResistanceNHEJ_parameters__sigma__get", (DL_FUNC) &EvoResistanceNHEJ_parameters__sigma__get, 1},
    {"EvoResistanceNHEJ_parameters__sigma__set", (DL_FUNC) &EvoResistanceNHEJ_parameters__sigma__set, 2},
    {"EvoResistanceNHEJ_trajectory__ctor", (DL_FUNC) &EvoResistanceNHEJ_trajectory__ctor, 1},
    {"EvoResistanceNHEJ_trajectory__x", (DL_FUNC) &EvoResistanceNHEJ_trajectory__x, 2},
    {"EvoResistanceNHEJ_trajectory__t_fix__get", (DL_FUNC) &EvoResistanceNHEJ_trajectory__t_fix__get, 1},
    {"EvoResistanceNHEJ_trajectory__t_fix__set", (DL_FUNC) &EvoResistanceNHEJ_trajectory__t_fix__set, 2},
    {"EvoResistanceNHEJ_fixation_probability__ctor", (DL_FUNC) &EvoResistanceNHEJ_fixation_probability__ctor, 2},
    {"EvoResistanceNHEJ_fixation_probability__pi", (DL_FUNC) &EvoResistanceNHEJ_fixation_probability__pi, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_EvoResistanceNHEJ(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
