# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Probability of resistance through de novo mutation.
#'
#' p_mu calculates the probability of resistance from de novo mutations. This is the probability of any mutation being resistant in t<tfix.
#'
#' @param P Parameter object. Create this using the "parameters()" constructor.
#' @param T Trajectory object. Create this using the "trajectory()" constructor.
#' @param F Fixation_probability object. Create this using the "fixation_probability()" constructor.
#' @export
p_mu <- function(P, T, F) {
    .Call('EvoResistanceNHEJ_p_mu', PACKAGE = 'EvoResistanceNHEJ', P, T, F)
}

#' Probability of resistance through NHEJ.
#'
#' p_delta calculates the probability of resistance from NHEJ during driver homing. This is the probability of any mutation being resistant in t<tfix.
#'
#' @param P Parameter object. Create this using the "parameters()" constructor.
#' @param T Trajectory object. Create this using the "trajectory()" constructor.
#' @param F Fixation_probability object. Create this using the "fixation_probability()" constructor.
#' @export
p_delta <- function(P, T, F) {
    .Call('EvoResistanceNHEJ_p_delta', PACKAGE = 'EvoResistanceNHEJ', P, T, F)
}

#' Probability of resistance through standing genetic variation.
#'
#' p_sgv calculates the probability of resistance existing as standing genetic variation. This is the probability of resistance becoming fixed during t<tfix.
#'
#' @param P Parameter object. Create this using the "parameters()" constructor.
#' @param F Fixation_probability object. Create this using the "fixation_probability()" constructor.
#' @export
p_sgv <- function(P, F) {
    .Call('EvoResistanceNHEJ_p_sgv', PACKAGE = 'EvoResistanceNHEJ', P, F)
}

parameters__ctor <- function(x0, c, delta, mu, sdo, sdr, sro, sdd, srr, Ne, N, sigma) {
    .Call('EvoResistanceNHEJ_parameters__ctor', PACKAGE = 'EvoResistanceNHEJ', x0, c, delta, mu, sdo, sdr, sro, sdd, srr, Ne, N, sigma)
}

parameters__x0__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__x0__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__x0__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__x0__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__c__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__c__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__c__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__c__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__delta__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__delta__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__delta__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__delta__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__mu__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__mu__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__mu__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__mu__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__sdo__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__sdo__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__sdo__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__sdo__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__sdr__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__sdr__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__sdr__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__sdr__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__sro__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__sro__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__sro__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__sro__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__sdd__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__sdd__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__sdd__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__sdd__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__srr__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__srr__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__srr__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__srr__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__Ne__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__Ne__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__Ne__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__Ne__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__N__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__N__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__N__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__N__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

parameters__sigma__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_parameters__sigma__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

parameters__sigma__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_parameters__sigma__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

trajectory__ctor <- function(P) {
    .Call('EvoResistanceNHEJ_trajectory__ctor', PACKAGE = 'EvoResistanceNHEJ', P)
}

trajectory__x <- function(obj_, t) {
    .Call('EvoResistanceNHEJ_trajectory__x', PACKAGE = 'EvoResistanceNHEJ', obj_, t)
}

trajectory__t_fix__get <- function(obj_) {
    .Call('EvoResistanceNHEJ_trajectory__t_fix__get', PACKAGE = 'EvoResistanceNHEJ', obj_)
}

trajectory__t_fix__set <- function(obj_, value) {
    invisible(.Call('EvoResistanceNHEJ_trajectory__t_fix__set', PACKAGE = 'EvoResistanceNHEJ', obj_, value))
}

fixation_probability__ctor <- function(P, T) {
    .Call('EvoResistanceNHEJ_fixation_probability__ctor', PACKAGE = 'EvoResistanceNHEJ', P, T)
}

fixation_probability__pi <- function(obj_, t) {
    .Call('EvoResistanceNHEJ_fixation_probability__pi', PACKAGE = 'EvoResistanceNHEJ', obj_, t)
}

