# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p_mu <- function(P, T, F) {
    .Call('EvoResistance_p_mu', PACKAGE = 'EvoResistance', P, T, F)
}

p_delta <- function(P, T, F) {
    .Call('EvoResistance_p_delta', PACKAGE = 'EvoResistance', P, T, F)
}

p_sgv <- function(P, F) {
    .Call('EvoResistance_p_sgv', PACKAGE = 'EvoResistance', P, F)
}

parameters__ctor <- function(x0, c, delta, mu, sdo, sdr, sro, srr, Ne, N, sigma) {
    .Call('EvoResistance_parameters__ctor', PACKAGE = 'EvoResistance', x0, c, delta, mu, sdo, sdr, sro, srr, Ne, N, sigma)
}

parameters__x0__get <- function(obj_) {
    .Call('EvoResistance_parameters__x0__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__x0__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__x0__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__c__get <- function(obj_) {
    .Call('EvoResistance_parameters__c__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__c__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__c__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__delta__get <- function(obj_) {
    .Call('EvoResistance_parameters__delta__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__delta__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__delta__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__mu__get <- function(obj_) {
    .Call('EvoResistance_parameters__mu__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__mu__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__mu__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__sdo__get <- function(obj_) {
    .Call('EvoResistance_parameters__sdo__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__sdo__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__sdo__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__sdr__get <- function(obj_) {
    .Call('EvoResistance_parameters__sdr__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__sdr__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__sdr__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__sro__get <- function(obj_) {
    .Call('EvoResistance_parameters__sro__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__sro__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__sro__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__srr__get <- function(obj_) {
    .Call('EvoResistance_parameters__srr__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__srr__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__srr__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__Ne__get <- function(obj_) {
    .Call('EvoResistance_parameters__Ne__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__Ne__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__Ne__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__N__get <- function(obj_) {
    .Call('EvoResistance_parameters__N__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__N__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__N__set', PACKAGE = 'EvoResistance', obj_, value))
}

parameters__sigma__get <- function(obj_) {
    .Call('EvoResistance_parameters__sigma__get', PACKAGE = 'EvoResistance', obj_)
}

parameters__sigma__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_parameters__sigma__set', PACKAGE = 'EvoResistance', obj_, value))
}

trajectory__ctor <- function(P) {
    .Call('EvoResistance_trajectory__ctor', PACKAGE = 'EvoResistance', P)
}

trajectory__x <- function(obj_, t) {
    .Call('EvoResistance_trajectory__x', PACKAGE = 'EvoResistance', obj_, t)
}

trajectory__t_fix__get <- function(obj_) {
    .Call('EvoResistance_trajectory__t_fix__get', PACKAGE = 'EvoResistance', obj_)
}

trajectory__t_fix__set <- function(obj_, value) {
    invisible(.Call('EvoResistance_trajectory__t_fix__set', PACKAGE = 'EvoResistance', obj_, value))
}

fixation_probability__ctor <- function(P, T) {
    .Call('EvoResistance_fixation_probability__ctor', PACKAGE = 'EvoResistance', P, T)
}

fixation_probability__pi <- function(obj_, t) {
    .Call('EvoResistance_fixation_probability__pi', PACKAGE = 'EvoResistance', obj_, t)
}

