## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: 590cf215133196dbebde94ad5b480089

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib EvoResistance
NULL

##' Parameters object for EvoResistance simulations.
##' 
##' This creates an object "Parameters" that contains all of the parameters for the simulation. It is the input for all further classes and functions used to calulate the allele frequences and probability of mutation from different sources.
##' @param x0: Introduction frequency of driver allele.
##' @param c: Cleavage rate in drive/wild-type heterozygotes.
##' @param delta: Fraction of cleavage events resulting in a resistant allele by NHEJ.
##' @param mu: Mutation rate of wild-type alleles, resulting in resistant allele.
##' @param sdo: Fitness cost of driver/wild-type heterozygote.
##' @param sdr: Fitness cost of driver/resistant heterozygote.
##' @param sro: Fitness cost of resistant/wild-type heterozygote.
##' @param sdd: Fitness cost of driver homozote.
##' @param srr: Fitness cost of resistant homozygote.
##' @param Ne: Variance effective population size.
##' @param N: Census population size.
##' @param sigma: Precision for simulations.
##' @export
`parameters` <- function(x0, c, delta, mu, sdo, sdr, sro, sdd, srr, Ne, N, sigma) {
  parameters__ctor(x0, c, delta, mu, sdo, sdr, sro, sdd, srr, Ne, N, sigma)
}
.R6_parameters <-
  R6::R6Class(
    "parameters",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      x0 = function(value) {
        if (missing(value)) {
          parameters__x0__get(self)
        } else {
          parameters__x0__set(self, value)
        }
      },
      c = function(value) {
        if (missing(value)) {
          parameters__c__get(self)
        } else {
          parameters__c__set(self, value)
        }
      },
      delta = function(value) {
        if (missing(value)) {
          parameters__delta__get(self)
        } else {
          parameters__delta__set(self, value)
        }
      },
      mu = function(value) {
        if (missing(value)) {
          parameters__mu__get(self)
        } else {
          parameters__mu__set(self, value)
        }
      },
      sdo = function(value) {
        if (missing(value)) {
          parameters__sdo__get(self)
        } else {
          parameters__sdo__set(self, value)
        }
      },
      sdr = function(value) {
        if (missing(value)) {
          parameters__sdr__get(self)
        } else {
          parameters__sdr__set(self, value)
        }
      },
      sro = function(value) {
        if (missing(value)) {
          parameters__sro__get(self)
        } else {
          parameters__sro__set(self, value)
        }
      },
      sdd = function(value) {
        if (missing(value)) {
          parameters__sdd__get(self)
        } else {
          parameters__sdd__set(self, value)
        }
      },
      srr = function(value) {
        if (missing(value)) {
          parameters__srr__get(self)
        } else {
          parameters__srr__set(self, value)
        }
      },
      Ne = function(value) {
        if (missing(value)) {
          parameters__Ne__get(self)
        } else {
          parameters__Ne__set(self, value)
        }
      },
      N = function(value) {
        if (missing(value)) {
          parameters__N__get(self)
        } else {
          parameters__N__set(self, value)
        }
      },
      sigma = function(value) {
        if (missing(value)) {
          parameters__sigma__get(self)
        } else {
          parameters__sigma__set(self, value)
        }
      }))

##' Trajectory object for EvoResistance simulations.
##' 
##' This class calculates the driver allele frequency and stores it as a vector. It runs until the allele frequency is >= 1-1/(2*P.N) or if the time exceeds 1e4. 
##' @param P: Parameter object. Create this using the "parameters()" constructor. 
##' @export
`trajectory` <- function(P) {
  trajectory__ctor(P)
}
.R6_trajectory <-
  R6::R6Class(
    "trajectory",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      x = function(t) {
        trajectory__x(self, t)
      }),
    active=list(
      t_fix = function(value) {
        if (missing(value)) {
          trajectory__t_fix__get(self)
        } else {
          trajectory__t_fix__set(self, value)
        }
      }))

##' Fixation_probability object for EvoResistance simulations.      
##' 
##' This class calculates the fixation probability of the driver allele.
##' @param P: Parameter object. Create this using the "parameters()" constructor.
##' @param T: Trajectory object. Create this using the "trajectory()" constructor.
##' @export
`fixation_probability` <- function(P, T) {
  fixation_probability__ctor(P, T)
}
.R6_fixation_probability <-
  R6::R6Class(
    "fixation_probability",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      pi = function(t) {
        fixation_probability__pi(self, t)
      }),
    active=list())


