## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: ba44f1975da5c576998f9ceda6bfe69f

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib EvoResistance
NULL

##' parameters
##' @param x0: dunno what this is
##' @export
`parameters` <- function(x0, c, delta, mu, sdo, sdr, sro, srr, Ne, N, sigma) {
  parameters__ctor(x0, c, delta, mu, sdo, sdr, sro, srr, Ne, N, sigma)
}
.R6_parameters <-
  R6::R6Class(
    "parameters",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      x0 = function(value) {
        if (missing(value)) {
          parameters__x0__get(self)
        } else {
          parameters__x0__set(self, value)
        }
      },
      c = function(value) {
        if (missing(value)) {
          parameters__c__get(self)
        } else {
          parameters__c__set(self, value)
        }
      },
      delta = function(value) {
        if (missing(value)) {
          parameters__delta__get(self)
        } else {
          parameters__delta__set(self, value)
        }
      },
      mu = function(value) {
        if (missing(value)) {
          parameters__mu__get(self)
        } else {
          parameters__mu__set(self, value)
        }
      },
      sdo = function(value) {
        if (missing(value)) {
          parameters__sdo__get(self)
        } else {
          parameters__sdo__set(self, value)
        }
      },
      sdr = function(value) {
        if (missing(value)) {
          parameters__sdr__get(self)
        } else {
          parameters__sdr__set(self, value)
        }
      },
      sro = function(value) {
        if (missing(value)) {
          parameters__sro__get(self)
        } else {
          parameters__sro__set(self, value)
        }
      },
      srr = function(value) {
        if (missing(value)) {
          parameters__srr__get(self)
        } else {
          parameters__srr__set(self, value)
        }
      },
      Ne = function(value) {
        if (missing(value)) {
          parameters__Ne__get(self)
        } else {
          parameters__Ne__set(self, value)
        }
      },
      N = function(value) {
        if (missing(value)) {
          parameters__N__get(self)
        } else {
          parameters__N__set(self, value)
        }
      },
      sigma = function(value) {
        if (missing(value)) {
          parameters__sigma__get(self)
        } else {
          parameters__sigma__set(self, value)
        }
      }))

##' trajectory
##' @param P: dunno what this is
##' @export
`trajectory` <- function(P) {
  trajectory__ctor(P)
}
.R6_trajectory <-
  R6::R6Class(
    "trajectory",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      x = function(t) {
        trajectory__x(self, t)
      }),
    active=list(
      t_fix = function(value) {
        if (missing(value)) {
          trajectory__t_fix__get(self)
        } else {
          trajectory__t_fix__set(self, value)
        }
      }))

##' fixation_probability
##' @param P: dunno what this is
##' @param T: dunno what this is
##' @export
`fixation_probability` <- function(P, T) {
  fixation_probability__ctor(P, T)
}
.R6_fixation_probability <-
  R6::R6Class(
    "fixation_probability",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      pi = function(t) {
        fixation_probability__pi(self, t)
      }),
    active=list())


